server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chatroom?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/static/
    suffix: .html
    mode: HTML
mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml
  type-aliases-package: com.nore.chatroom.userDTO
  configuration:
    map-underscore-to-camel-case: true